apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: gceme
    role: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gceme
      role: db
  template:
    metadata:
      name: db
      labels:
        app: gceme
        role: db
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 3306
          name: mysql
---
kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  ports:
  - name: http
    port: 8080
  selector:
    role: backend
    app: gceme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gceme
      role: backend
  template:
    metadata:
      name: backend
      labels:
        app: gceme
        role: backend
    spec:
      containers:
      - name: backend
        image: REPLACE_WITH_IMAGE
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        imagePullPolicy: Always
        command: ["sh", "-c", "app -run-migrations -mode=backend -run-migrations -port=8080 -db-host=db -db-password=$MYSQL_ROOT_PASSWORD" ]
        ports:
        - name: backend
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: gceme
    role: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gceme
      role: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: gceme
        role: frontend
    spec:
      containers:
      - name: frontend
        image: REPLACE_WITH_IMAGE
        imagePullPolicy: Always
        command: ["app", "-mode=frontend", "-backend-service=http://backend:8080", "-port=80"]
        ports:
        - name: frontend
          containerPort: 80
