apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  password: cm9vdA==
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: gceme
    role: db
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: gceme
    role: db
spec:
  containers:
  - image: mysql:5.6
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
    ports:
    - containerPort: 3306
      name: mysql
---
kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    role: backend
    app: gceme
---
kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    app: gceme
    role: backend
spec:
  containers:
  - name: backend
    image: gcr.io/barry-williams/sample-k8s-app:1.0.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
    command: ["sh", "-c", "app -mode=backend -run-migrations -port=8080 -db-host=db -db-password=$MYSQL_ROOT_PASSWORD" ]
    ports:
    - name: backend
      containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: gceme
    role: frontend
---
kind: Pod
apiVersion: v1
metadata:
  name: frontend
  labels:
    app: gceme
    role: frontend
spec:
  containers:
  - name: frontend
    image: gcr.io/barry-williams/sample-k8s-app:1.0.0
    command: ["app", "-mode=frontend", "-backend-service=http://backend:8080", "-port=80"]
    ports:
    - name: frontend
      containerPort: 80
